export const ASYNC_FIRING = 'ASYNC_FIRING';
export const ASYNC_STATE = 'ASYNC_STATE';

export const ASYNC_INDEX = 'ASYNC_INDEX';
export const ASYNC_INDEX_SUCCESS = 'ASYNC_INDEX_SUCCESS';
export const ASYNC_INDEX_FAILURE = 'ASYNC_INDEX_FAILURE';

export const ASYNC_STORE = 'ASYNC_STORE';
export const ASYNC_STORE_SUCCESS = 'ASYNC_STORE_SUCCESS';
export const ASYNC_STORE_FAILURE = 'ASYNC_STORE_FAILURE';

export const ASYNC_UPDATE = 'ASYNC_UPDATE';
export const ASYNC_UPDATE_SUCCESS = 'ASYNC_UPDATE_SUCCESS';
export const ASYNC_UPDATE_FAILURE = 'ASYNC_UPDATE_FAILURE';

export const ASYNC_DESTROY = 'ASYNC_DESTROY';
export const ASYNC_DESTROY_SUCCESS = 'ASYNC_DESTROY_SUCCESS';
export const ASYNC_DESTROY_FAILURE = 'ASYNC_DESTROY_FAILURE';
